name: myntra_test_app
description: A flutter app to showcase online shopping portal using Provider architecture. FireStore has been used as backend for this app.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  cloud_firestore: ^0.13.4
  cupertino_icons: ^0.1.2
  firebase_auth: 0.15.3
  #  firebase_core: 0.4.4+3
  firebase_storage: ^3.1.3
  flutter_test:
    sdk: flutter
  flutter_widgets: ^0.1.10
  http: ^0.12.0+4
  provider: ^4.0.4
  progress_hud: ^1.1.0
  shared_preferences: ^0.5.6+3

dev_dependencies:


dependency_overrides:
  firebase_core: 0.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/social/
    - assets/images/

